flat_dev-hyperparameterand-formula-search.Rmd:
  path: dev/flat_dev-hyperparameterand-formula-search.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/hyperparameter-and-formula-search.Rmd
  inflate:
    flat_file: dev/flat_dev-hyperparameterand-formula-search.Rmd
    vignette_name: Hyperparameter and Formula Search
    open_vignette: true
    check: true
    document: true
    overwrite: ask
flat_full.Rmd:
  path: dev/flat_full.Rmd
  state: active
  R:
  - R/bulk_update_role.R
  - R/make_bound_statements.R
  - R/step_saturation.R
  tests: tests/testthat/test-step_saturation.R
  vignettes: vignettes/demonstration-of-parts-of-the-package.Rmd
  inflate:
    flat_file: dev/flat_full.Rmd
    vignette_name: Demonstration of Parts of the Package
    open_vignette: true
    check: true
    document: true
    overwrite: ask
