---
title: "flat_dev-hyperparameterand-formula-search.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# dev_hyperparameterand_formula_search_rmd

```{r function-dev_hyperparameterand_formula_search_rmd}
#' dev_hyperparameterand_formula_search_rmd Title
#'
#' @return 1
#' @export
#'
#' @examples
dev_hyperparameterand_formula_search_rmd <- function() {
  1
}
```

```{r examples-dev_hyperparameterand_formula_search_rmd}
dev_hyperparameterand_formula_search_rmd()
```

```{r tests-dev_hyperparameterand_formula_search_rmd}
test_that("dev_hyperparameterand_formula_search_rmd works", {

})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_dev-hyperparameterand-formula-search.Rmd", vignette_name = "Go further")
```

