# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' function to add saturation trasnformations to a recipe
#'
#' @param recipe a recipes::recipe
#' @param ... variables in recipe to be effected by the step
#' @param role defaults to NA, set to a string to change the role of the transformed variables
#' @param retention defaults to .5, the amount of impact retained from the previous time period
#' @param id default value will work most often, but can be set manually for use with tuning fuctions
#'
#' @return
#' a recipe with the new adstock step appended
#' @export
#'
#' @examples
#'
#' suppressMessages(suppressWarnings(library(tidyverse)))
#' suppressMessages(suppressWarnings(library(recipes)))
#' suppressMessages(suppressWarnings(library(tune)))
#' suppressMessages(suppressWarnings(library(dials)))
#' suppressMessages(suppressWarnings(library(mostlytidyMMM)))
#' #create two datasets:
#' mktdata<-rbind(tibble(prod='brand',store='store1',
#'                       sales=c(100.,100.,100.,100.,100.),
#'                       tv=c(10.,100.,0.,0.,100),
#'                       search=c(0,10,20,50.,50.)) ,
#'                tibble(prod='brand',store='store2',
#'                       sales=c(10.,10,10,10,10),tv=c(0.,0,0,0,0),
#'                       search=c(0.,2,2,0,0) ) ) |> 
#'   group_by(prod,store)
#'
#' mktdata2<-tibble(prod='brand',store='all',sales=100,tv=1000,search=1000) |> group_by(prod,store)
#'
#' #build a recipe with two different adstock steps -- could be done in one step
#' rec_obj <-  recipe(sales ~ ., data = mktdata) |> step_adstock(tv,retention=.5,groups=c('prod','store')) |>
#'   step_adstock(search,retention=.5,groups=c('prod','store')) |>
#'   prep(training = mktdata)
#'
#' #showing off the custom print function
#' print(rec_obj)
#'
#' #see the final transformed output
#' bake(rec_obj,mktdata)
#'
#' #note what happens to store = 'all' in mktdata2:
#' bake(rec_obj,mktdata2)
#'
#' #check to make sure that per-variable application of the step_adstock and step-saturation do not break the grouping structure even though
#' #the output tibble from bake is ungrouped (irritatingly)
#'
#' rec_both_steps<-recipe(sales~.,data=mktdata) |> 
#'   step_adstock(tv,retention=.1) |> step_saturation(tv,asymptote=1000,saturation_speed=.001) |>
#'   step_adstock(search,retention=.1)  |> prep()
#'
#'
#' bake(rec_both_steps,mktdata)
#'
step_adstock <- function(
    recipe, 
    ..., 
    role = NA, 
    trained = FALSE, 
    options = list( names = TRUE), #change to be range of retention
    skip = FALSE,
    retention=.5,
    groups=c('prod','store'),
    adstocks=NULL,
    id = rand_id("adstock")
) {
  
  add_step(
    recipe, 
    step_adstock_new(
      terms = enquos(...), 
      trained = trained,
      role = role, 
      options = options,
      skip = skip,
      id = id,
      retention=retention,
      adstocks=adstocks,
      groups=groups
    )
  )
}

#' internal function used in create recipe steps
#'
#'
#' @return
#' a recipe sep of type saturation
#' @export
#' 
#' @example
#' 
step_adstock_new <-   function(terms, role, trained, retention, adstocks, groups,options, skip, id) {
    step(
      subclass = "adstock", 
      terms = terms,
      role = role,
      trained = trained,
      adstocks=adstocks,
      retention=retention,
      groups=groups,
      options = options,
      skip = skip,
      id = id
      
    )
  }

#' Prep method for step_adstock
#' @param x step or recipe
#' @param training dataset used for prep
#'
#' @return
#' a recipe step of type adstock
#' @export
#' @export prep.step_adstock
#' @example
#' 
#' @importFrom recipes prep
#' 
prep.step_adstock <- function(x, training, info = NULL, ...) {
  col_names <- recipes_eval_select(x$terms, training, info) 
  
  ## We'll use the names later so make sure they are available
  if (x$options$names == FALSE) {
    rlang::abort("`names` should be set to TRUE")
  }
  
  step_adstock_new(terms=x$terms,
                   role=x$role,
                   trained=TRUE,
                   retention=x$retention,
                   groups=x$groups,
                   adstocks=col_names,
                   options=x$options,
                   skip=x$skip,
                   id=x$id
  )
}
#' function used to compute adstock transformation
#' 
#' @param x numeric vector or time series of values to be adstocked
#' @param retain between 0 and 1, the amount of previous time points value that effects the current time point
#'
#' @return
#' a numeric vector that shows the adstocked values of x
#' @export
#' 
get_adstock<-function(x,retain){
  x<-as.numeric(stats::filter(x,retain,'recursive'))
  return(x)
}
#' bake method for step_adstock
#' 
#' @param object is recipe 
#' @param new_data data.frame or tibble to be baked
#'
#' @return
#' data that is transformed
#' @export
#' @export bake.step_adstock
#' 
#' @example
#' 
#' @importFrom recipes bake
#' 
bake.step_adstock<-function(object,new_data,...){
  vars<-names(object$adstocks)
  groupings<-object$groups#as.character(groups(new_data))

  if(length(groupings)==0){rlang::warn("No grouping vars in data for step_adstock -- assumes data is one continous time series!!!  \nIf this isn't true, group and sort the data appropriately!")}
  
  stocks<-new_data |> group_by(across(all_of(groupings))) |> reframe(across(all_of(vars), function(x){get_adstock(x,object$retention)} ))
  
  new_data[,vars]<-stocks[,vars]
  
  
  if(length(groupings)>0){
    stocks<-new_data |> group_by(across(all_of(groupings))) |> reframe(across(all_of(vars), function(x){get_adstock(x,object$retention)} ))
    new_data<-as_tibble(new_data) |> group_by(across(all_of(groupings)))
  }
  else{
    stocks<-new_data |> reframe(across(all_of(vars), function(x){get_adstock(x,object$retention)} ))
    
  }
  return(new_data)
  
}

#' custom print method for adstock steps
#' @param x is recipe or step
#'
#' @return
#' descriptive output to console
#' @export
#' @export print.step_adstock
#' @example
#' 

print.step_adstock <-
  function(x, width = max(20, options()$width - 35), ...) {
    
    print_step(
      # Names before prep (could be selectors)
      untr_obj = x$terms,
      # Names after prep:
      tr_obj = names(x$adstocks),
      # Has it been prepped? 
      trained = x$trained,
      # An estimate of how many characters to print on a line: 
      width = width,
      title=paste("Adstock Transformation with retention",x$retention,"on"),
      case_weights=x$case_weights
    )
    invisible(x)
  }

#' tunable method for step_adstock
#' @param x is a step or recipe
#'
#' @return
#' a tibble interpretable by dials and tune as hyperparameter information
#' @export
#' @export tunable.step_adstock
#' 
#' @importFrom tune tunable
#' 
tunable.step_adstock <- function (x, ...) {
  tibble::tibble(
    name = c("retention"),
    call_info = list(list( fun = "retention")),
    source = "recipe",
    component = "step_adstock",
    component_id = x$id
  )
}

#' establishing retention as a dial using new_quant_param
#'
#' @param range is the allowed range of retention for a specific hyperparameter
#'
#' @return
#' a quantitative tunable hyperparameter
#' @export
#' @importFrom dials new_quant_param
#' 
retention<-function(range=c(0,.8)){dials::new_quant_param(type='double',range=range,inclusive=c(TRUE,TRUE),
                                                   label=c(retention='retention'),finalize = NULL)}



# #' working around some fusen issue; re-exporting bake to this namespace
# #' @export
# bake<-recipes::bake
# 
# #' working around some fusen issue; re-exporting bake to this namespace
# #' @export
# prep<-recipes::prep
# 
# #' working around some fusen issue; re-exporting bake to this namespace
# #' @export
# tunable<-tune::tunable


#' function to add saturation trasnformations to a recipe
#'
#' @param recipe a recipes::recipe
#' @param ... variables in recipe to be effected by the step
#' @param role defaults to NA, set to a string to change the role of the transformed variables
#' @param asymptote defaults to 100, the asymptotic value of the saturation transformed variable
#' @param saturation_speed defaults to .05, controls how quickly the asymptote is approached
#' @param id default value will work most often, but can be set manually for use with tuning fuctions
#'
#' @return
#' a recipe with the new saturation step appended
#' @export
#'
#' @examples
#' #not run!
#' suppressMessages(suppressWarnings(library(tidyverse)))
#' suppressMessages(suppressWarnings(library(recipes)))
#' suppressMessages(suppressWarnings(library(tune)))
#' suppressMessages(suppressWarnings(library(dials)))
#' suppressMessages(suppressWarnings(library(mostlytidyMMM)))
#'
#' #create two datasets
#' mktdata<-rbind(tibble(prod='brand',store='store1',
#'                       sales=c(100,100,100,100,100),tv=c(10,100,0,0,100),
#'                       search=c(0,10,20,50,50)) ,
#'                tibble(prod='brand',store='store2',
#'                       sales=c(10,10,10,10,10),tv=c(0,0,0,0,0),
#'                       search=c(0,2,2,0,0) ) ) |> 
#'   group_by(prod,store)
#'
#' mktdata2<-tibble(prod='brand',store='all',
#'                  sales=100,tv=1000,search=1000) |> group_by(prod,store)
#'
#' #creating a recipe with a saturaiton step in it
#' rec_obj <-
#'  recipe(sales ~ ., data = mktdata) |>
#'  step_saturation(c(tv,search),asymptote=200,saturation_speed=.003 ) |>
#'  prep(training = mktdata)
#'
#' #showing what a tunable recipe looks liek:
#' rec_obj2<-  recipe(sales ~ ., data = mktdata) |>
#'   step_saturation(c(tv,search),asymptote=tune(),saturation_speed=tune() )
#'
#' extract_parameter_set_dials(rec_obj2)
#'
#'  #custom print shows values of saturation hyperparameters:
#'  print(rec_obj)
#'  #or shows that they are set to be tuned:
#'  print(rec_obj2)
#'  #producing the transformed dataset:
#'  bake(rec_obj,mktdata)
#'
step_saturation <- function(
    recipe, 
    ..., 
    role = NA, 
    trained = FALSE, 
    options = list( names = TRUE),
    skip = FALSE,
    asymptote=100,
    saturation_speed=.05,
    hills=NULL,
    id = rand_id("saturation")
) {
  
  add_step(
    recipe, 
    step_saturation_new(
      terms = enquos(...), 
      trained = trained,
      role = role, 
      options = options,
      skip = skip,
      id = id,
      asymptote=asymptote,
      saturation_speed=saturation_speed,
      hills=hills
    )
  )
}

#' internal function used in create recipe steps
#'
#'
#' @return
#' a recipe sep of type saturation
#' @export
step_saturation_new <- 
  function(terms, role, trained, asymptote,saturation_speed,hills, options, skip, id) {
    step(
      subclass = "saturation", 
      terms = terms,
      role = role,
      trained = trained,
      asymptote=asymptote,
      saturation_speed=saturation_speed,
      hills=hills,
      options = options,
      skip = skip,
      id = id
    )
  }

#' a monotonic saturation function with monotonic first deriviate used in recipes for preprocssing MMM data
#' 
#' @param x vector of numeric value to saturate
#' @param asymptote the asymptote of the transformed values; should probably exceed the max value in the modeled data
#' @param saturation_speed higher values approach the asymptote faster
#'
#'
#' @return
#' a numeric vector of transformed values
#' @export
#worker bee function
get_train_saturation<-function(x,asymptote,saturation_speed){
  stopifnot(length(asymptote) == 1)
  stopifnot(length(saturation_speed) == 1)
  x_scurve<-asymptote*(1-exp(-saturation_speed*x))
  
  return(x_scurve)
}

#' The saturation step prep method
#' 
#' @param x an object (step or recipe)
#' @param training  tibble used to provide data for training
#' 
#' @return
#' a prepped recipe or step
#' @export
#' @export prep.step_saturation
#' 
#' @importFrom recipes prep
#' 
prep.step_saturation <- function(x, training, info = NULL, ...) {
  
  #this will select the appropriate columns from the training set
  col_names <- recipes_eval_select(x$terms, training, info) 
  
  ## We'll use the names later so make sure they are available
  if (x$options$names == FALSE) {
    rlang::abort("`names` should be set to TRUE")
  }
  
  #transforms computed here
  step_saturation_new(terms=x$terms,
                      trained=TRUE,
                      role=x$role,
                      options=x$options,
                      skip=x$skip,
                      id=x$id,
                      asymptote=x$asymptote,
                      saturation_speed=x$saturation_speed,
                      hills=col_names
  )
  
}

#'The saturation bake method
#'
#' @param object recipe or step
#' @param mdata the data fed to the recipe or step
#'
#' @return
#'a transformed dataset
#'
#' @export
#' @export bake.step_saturation
#'
#' @importFrom recipes bake
bake.step_saturation<-function(object,new_data,...){
  vars<-names(object$hills)
  groupings<-as.character(groups(new_data))
  
  new_data[,vars]<-new_data[,object$hills] |> reframe(across(everything(),function(x){get_train_saturation(x,
                                                                                                            object$asymptote,object$saturation_speed)})) 
  if(length(groupings)>0) {new_data<-as_tibble(new_data) |> group_by(across(all_of(groupings)))}
  else{new_data<-as_tibble(new_data)}
  return(new_data)
  
}

#' print method for saturation steps
#' 
#' @param x step
#' @return
#' string
#' @export
#' @export print.step_saturation
#' 
print.step_saturation <-
  function(x, width = max(20, options()$width - 35), ...) {
    
    print_step(
      # Names before prep (could be selectors)
      untr_obj = x$terms,
      # Names after prep:
      tr_obj = names(x$hills),
      # Has it been prepped? 
      trained = x$trained,
      # An estimate of how many characters to print on a line: 
      width = width,
      title = paste("Saturation (asymptote=",x$asymptote,"saturation_speed=",x$saturation_speed,"Transformation on")
    )
    invisible(x)
  }

#'tunable method for saturation steps -- used by tune package to identify what each hyperparameter is.
#'
#' @param x step or recipe
#' @return
#'tibble that tune functions can evaluate as hyperparameter information
#' @export
#' @export tunable.step_saturation
#'
#' @importFrom tune tunable
tunable.step_saturation <- function (x, ...) {
  tibble::tibble(
    name = c("asymptote","saturation_speed"),
    call_info = list(list( fun = "asymptote"),list(fun='saturation_speed')),
    source = c("recipe","recipe"),
    component = c("step_saturation","step_saturation"),
    component_id = x$id
  )
}

#' dial (ie from the tune package) for asymptote
#' 
#' @param range defaults to c(100,300), should be a length2 numeric vector that has the minimum and maximum possible asymptotes for a given variable transformation.  In general the asymptote should be higher than the max value in the historical data.
#' @return
#' a quant param dial
#' @export
#' @importFrom dials new_quant_param
asymptote<-function(range=c(100,300)){dials::new_quant_param(type='double',range=range,inclusive=c(FALSE,TRUE),
                                                    label=c(asymptote='saturation asymptote'),finalize = NULL)}

#' dial (ie from the tune package) for saturation_speed
#' 
#' @param range defaults to c(.0001,.009), should be a length 2 numeric vector that has the minimum and maximum possible saturation speed. Small changes in this value have large impact of rate of saturation.
#' @return
#' a quant param dial
#' @export
#' @importFrom dials new_quant_param
saturation_speed<-function(range=c(.0001,.009)){dials::new_quant_param(type='double',range=range,inclusive=c(FALSE,FALSE),                                                            label=c(saturation_speed='saturation speed'),finalize = NULL)}

